spring:
  application:
    name: shopee-user-service
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8071/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/shopee_users_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    password: '123456'
  jpa:
    open-in-view: 'false'
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka-server

management:
  endpoints:
    web:
      exposure:
        include: '*'



server:
  port: '9001'
